spring:
  application:
    name: orders-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: ecommerce
    password: ecommerce

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: orders
    open-in-view: false

  flyway:
    schemas: orders
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

orders:
  kafka:
    topic: order.created
    partitions: 3
    replication-factor: 1

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
